name: Tomatect
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7
  geolocator: ^9.0.2
  http: ^0.13.3
  location: ^4.3.0
  camera: ^0.10.3+2
  rflutter_alert: ^2.0.7
  adv_image_picker: ^3.0.1
  image_picker_plus: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/page1.png
    - assets/images/clear.jpg
    - assets/images/cloudy.jpg
    - assets/images/rainy.jpg
    - assets/images/sunny.jpg
    - assets/images/thunderstorm.jpg
    - assets/images/default.jpg
    - assets/images/tomato.jpg
    - assets/images/plant.jpg
    - assets/images/tomato_disease.jpg
    - assets/images/tomato_survival_rate.jpg
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
